# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/http.d/default.conf
      - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      - APP_ENV=local
      - XDEBUG_CONFIG=client_host=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laravel
    # command: >
    #   sh -c "composer install --no-interaction --optimize-autoloader &&
    #           php artisan key:generate --force &&
    #           php artisan migrate &&
    #          /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    entrypoint: ["/var/www/html/entrypoint.sh"]
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Using same password as user for simplicity, or set a separate one
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
    driver: local